<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?= $this->view->info_usuario['nome'] ?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_tweets['total_tweet'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_seguindo['total_seguindo']?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_seguidores['total_seguidores']?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="post" action="/tweet">
						<textarea class="form-control" name="tweet" id="exampleFormControlTextarea1" placeholder="No que você está pensando, <?= $_SESSION['nome'] ?>?" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<?php
				foreach($this->view->tweets as $tweet)
				{
			?>	
			<div class="row tweet">
				
				<div class="col">
					
					<p><strong><?= $tweet['nome']; ?></strong> <small><span class="text text-muted">- <?= $tweet['data']; ?></span></small></p>
					<p><?= $tweet['tweet']; ?></p>

					<br />
					<?php if ($tweet['id_usuario'] == $_SESSION['id']) { ?>
						
						<div class="col d-flex justify-content-end">
							<a href="/delete?id_tweet= <?= $tweet['id']?>"> <button type="submit" class="btn btn-outline-danger"><small><i class="fas fa-trash"></i> Remover</small></button> </a>
						</div>
					

					<?php } ?>
				</div>
			</div>
			<?php } ?>
			
			<?php 
				$pagina_ativa = $this->view->pagina_ativa;
				$total_de_paginas = $this->view->total_de_paginas;

			?>	

			<div class="container">
				<div class="row ">
					<nav aria-label="Page navigation example" class="mt-5 dp-center">
					<ul class="pagination">
						<li class="page-item <?= $pagina_ativa != 1 ? '' : 'disabled' ?>"><a class="page-link " href="?pagina= <?= $pagina_ativa > 0  ? $pagina_ativa - 1 : '' ?>">Anterior</a></li>

						<?php 
						for( $x = 1; $x <= $total_de_paginas; $x++ ) { ?>

							<!-- Faz um if para indicar por meio da class active uma marcação na página atual -->
						<li class="page-item  <?= $x == $pagina_ativa ? 'active' : '' ?> "><a class="page-link" href="?pagina=<?= $x ?>?"><?= $x ?></a></li>
						<?php } ?>
						
						<li class="page-item <?= $pagina_ativa == $total_de_paginas ? 'disabled' : '' ?>"><a class="page-link" href="?pagina= <?= $pagina_ativa < $total_de_paginas ? $pagina_ativa + 1 : $total_de_paginas ?>" >Próximo</a></li>
					</ul>
					</nav>		
				</div>
			</div>
		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>

